version: "3.9"

networks:
  default:
    name: roll
    driver: bridge

volumes:
  shared-volume:

services:
  rolldice:
    depends_on:
      - jaeger
    build:
      context: .
      dockerfile: ./Dockerfile
    pid: "host"
    ports:
      - "8080:8080"
    volumes:
      - /proc:/host/proc
      - shared-volume:/app
  go-auto:
    depends_on:
      - rolldice
    image: otel/autoinstrumentation-go:v0.10.1-alpha
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_GO_AUTO_TARGET_EXE=/app/main
      - OTEL_SERVICE_NAME=rolldice
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - /proc:/host/proc
      - shared-volume:/app

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
